"use client"
import React, { useState, useEffect } from 'react';
import { resolveFileUrl } from '../../../../utils/resolveFileUrl';

// ─── Constants ───
const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
const STATUS_MSG_DURATION = 4000;

// ─── Types ───
interface Employee {
  id: string;
  name: string;
  fullName?: string;
  username?: string;
  photo1?: string;
}

interface WarningRequest {
  id: string;
  type: string;
  reason: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  autoGenerated?: boolean;
  createdAt: string;
  employee?: Employee;
}

export default function WarningsPage() {
  const [pending, setPending] = useState<WarningRequest[]>([]);
  const [history, setHistory] = useState<WarningRequest[]>([]);
  const [issued, setIssued] = useState<any[]>([]); // Added issued warnings state
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [tab, setTab] = useState<'pending' | 'history' | 'new' | 'issued'>('pending');
  const [loading, setLoading] = useState(true);

  // New warning request form
  const [selectedEmp, setSelectedEmp] = useState('');
  const [warningType, setWarningType] = useState('عدم إرسال تقرير');
  const [warningReason, setWarningReason] = useState('');
  const [statusMsg, setStatusMsg] = useState('');
  const [deletingWarningId, setDeletingWarningId] = useState<string | null>(null);

  const getToken = () => typeof window !== 'undefined' ? localStorage.getItem('token') : '';

  const fetchData = () => {
    const token = getToken();
    Promise.all([
      fetch(API_URL + '/users/warnings/pending', { headers: { 'Authorization': 'Bearer ' + token } }).then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).catch((err) => { console.error('فشل جلب التحذيرات المعلقة:', err); return []; }),
      fetch(API_URL + '/users/warnings/all', { headers: { 'Authorization': 'Bearer ' + token } }).then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).catch((err) => { console.error('فشل جلب سجل التحذيرات:', err); return []; }),
      fetch(API_URL + '/users/warnings/issued', { headers: { 'Authorization': 'Bearer ' + token } }).then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).catch((err) => { console.error('فشل جلب التحذيرات الصادرة:', err); return []; }),
      fetch(API_URL + '/users', { headers: { 'Authorization': 'Bearer ' + token } }).then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).catch((err) => { console.error('فشل جلب الموظفين:', err); return []; }),
    ]).then(([p, h, i, e]) => {
      setPending(Array.isArray(p) ? p : []);
      setHistory(Array.isArray(h) ? h : []);
      setIssued(Array.isArray(i) ? i : []);
      setEmployees(Array.isArray(e) ? e : []);
      setLoading(false);
    });
  };

  useEffect(() => { fetchData(); }, []);

  const handleDeleteWarning = async (id: string) => {
    if (!confirm('هل أنت متأكد من حذف هذا التحذير؟ سيتم مسحه نهائياً من سجل الموظف.')) return;
    setDeletingWarningId(id);
    try {
      const res = await fetch(`${API_URL}/users/warnings/issued/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': 'Bearer ' + getToken() }
      });
      if (res.ok) {
        setStatusMsg('تم رفع التحذير بنجاح! 👍');
        fetchData();
        setTimeout(() => setStatusMsg(''), STATUS_MSG_DURATION);
      } else {
        alert('حدث خطأ أثناء رفع التحذير.');
      }
    } catch (err) {
      alert('خطأ في الاتصال بالخادم.');
    } finally {
      setDeletingWarningId(null);
    }
  };

  const handleApprove = async (id: string) => {
    try {
      await fetch(API_URL + '/users/warnings/' + id + '/approve', {
        method: 'POST', headers: { 'Authorization': 'Bearer ' + getToken() }
      });
      fetchData();
    } catch (err) {
      console.error('فشل الموافقة على التحذير:', err);
    }
  };

  const handleReject = async (id: string) => {
    try {
      await fetch(API_URL + '/users/warnings/' + id + '/reject', {
        method: 'POST', headers: { 'Authorization': 'Bearer ' + getToken() }
      });
      fetchData();
    } catch (err) {
      console.error('فشل رفض التحذير:', err);
    }
  };

  const handleCreateRequest = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedEmp) return;
    try {
      const res = await fetch(API_URL + '/users/warnings/request', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + getToken() },
        body: JSON.stringify({ employeeId: selectedEmp, type: warningType, reason: warningReason })
      });
      if (res.ok) {
        setStatusMsg('تم إنشاء طلب التحذير بنجاح! ينتظر الموافقة.');
        setWarningReason('');
        setTab('pending');
        fetchData();
        setTimeout(() => setStatusMsg(''), STATUS_MSG_DURATION);
      } else {
        const data = await res.json().catch(() => ({}));
        console.error('فشل إنشاء التحذير:', data);
      }
    } catch (err) {
      console.error('خطأ في إنشاء التحذير:', err);
    }
  };

  /** Safe first character accessor */
  const getInitial = (text?: string): string => {
    if (!text || text.length === 0) return '؟';
    return text[0];
  };

  if (loading) return <div className="p-8 text-onSurfaceVariant">جاري التحميل...</div>;

  return (
    <div className="flex flex-col gap-6 max-w-7xl mx-auto animate-in fade-in duration-500 pb-10">
      <header className="flex justify-between items-center">
        <div>
          <h1 className="text-display font-bold text-3xl mb-1 text-onSurface">مركز التحذيرات الذكي</h1>
          <p className="text-onSurfaceVariant text-sm">يتم عرض طلبات التحذير هنا للموافقة عليها أو رفضها قبل إصدارها للموظف</p>
        </div>
        <div className="flex items-center gap-2">
          {pending.length > 0 && (
            <span className="bg-error text-white px-4 py-2 rounded-full font-bold text-sm animate-pulse">
              {pending.length} بانتظار الموافقة
            </span>
          )}
        </div>
      </header>

      {statusMsg && <div className="bg-success/10 text-success p-3 rounded-xl text-sm font-bold border border-success/20">{statusMsg}</div>}

      {/* Tabs */}
      <div className="flex gap-2 flex-wrap bg-surfaceContainerLowest p-1.5 rounded-2xl w-fit">
        <button onClick={() => setTab('pending')} className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${tab === 'pending' ? 'gradient-bg text-white shadow-ambient' : 'text-onSurfaceVariant hover:bg-surfaceContainerHigh'}`}>
          بانتظار الموافقة ({pending.length})
        </button>
        <button onClick={() => setTab('new')} className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${tab === 'new' ? 'gradient-bg text-white shadow-ambient' : 'text-onSurfaceVariant hover:bg-surfaceContainerHigh'}`}>
          إنشاء طلب تحذير
        </button>
        <button onClick={() => setTab('issued')} className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${tab === 'issued' ? 'gradient-bg text-white shadow-ambient' : 'text-onSurfaceVariant hover:bg-surfaceContainerHigh'}`}>
          التحذيرات الصادرة ({issued.length})
        </button>
        <button onClick={() => setTab('history')} className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${tab === 'history' ? 'gradient-bg text-white shadow-ambient' : 'text-onSurfaceVariant hover:bg-surfaceContainerHigh'}`}>
          السجل الكامل ({history.length})
        </button>
      </div>

      {/* Pending Tab */}
      {tab === 'pending' && (
        <div className="flex flex-col gap-4">
          {pending.length === 0 ? (
            <div className="text-center p-16 text-onSurfaceVariant flex flex-col items-center gap-3 glass-card">
              <span className="text-5xl opacity-40">✅</span>
              <p className="font-bold">لا توجد طلبات تحذير بانتظار الموافقة</p>
            </div>
          ) : pending.map(req => (
            <div key={req.id} className="glass-card p-6 border-r-4 border-warning relative overflow-hidden">
              <div className="flex items-start gap-4">
                <div className="relative shrink-0">
                  {req.employee?.photo1 ? (
                    <img src={resolveFileUrl(req.employee.photo1)} className="w-14 h-14 object-cover rounded-full border-2 border-error/30" alt={`صورة ${req.employee?.fullName || req.employee?.name || 'موظف'}`} />
                  ) : (
                    <div className="w-14 h-14 bg-error/10 text-error rounded-full flex items-center justify-center font-bold text-xl">{getInitial(req.employee?.name)}</div>
                  )}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <p className="font-bold text-lg">{req.employee?.fullName || req.employee?.name}</p>
                    {req.autoGenerated && <span className="text-[10px] bg-tertiary/10 text-tertiary px-2 py-0.5 rounded font-bold">تحذير تلقائي 🤖</span>}
                  </div>
                  <div className="flex items-center gap-3 mb-3">
                    <span className="text-xs font-bold bg-error/10 text-error px-3 py-1 rounded-full">{req.type}</span>
                    <span className="text-[10px] text-onSurfaceVariant">{new Date(req.createdAt).toLocaleString('ar-EG')}</span>
                  </div>
                  <p className="text-sm text-onSurfaceVariant bg-surfaceContainerLow p-3 rounded-xl">{req.reason}</p>
                </div>
              </div>
              <div className="flex gap-3 mt-4 justify-end">
                <button onClick={() => handleReject(req.id)} className="bg-surfaceContainerHigh text-onSurface px-6 py-2.5 rounded-xl font-bold text-sm hover:bg-surfaceContainerHighest transition-colors">رفض الطلب</button>
                <button onClick={() => handleApprove(req.id)} className="bg-error text-white px-6 py-2.5 rounded-xl font-bold text-sm hover:opacity-90 transition-opacity shadow-lg shadow-error/20">✓ الموافقة وإصدار التحذير</button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* New Warning Tab */}
      {tab === 'new' && (
        <div className="glass-card p-6 max-w-xl">
          <h2 className="text-lg font-bold mb-6">⚠️ إنشاء طلب تحذير جديد</h2>
          <form onSubmit={handleCreateRequest} className="flex flex-col gap-4">
            <div>
              <label className="text-xs font-bold text-onSurfaceVariant block mb-2">اختر الموظف:</label>
              <select required value={selectedEmp} onChange={e => setSelectedEmp(e.target.value)} className="w-full bg-surfaceContainerLow p-3 rounded-xl border border-outlineVariant/20 outline-none focus:ring-2 focus:ring-primary text-sm font-bold">
                <option value="">— اختر موظفاً —</option>
                {employees.map(emp => <option key={emp.id} value={emp.id}>{emp.fullName || emp.name} (@{emp.username})</option>)}
              </select>
            </div>
            <div>
              <label className="text-xs font-bold text-onSurfaceVariant block mb-2">نوع التحذير:</label>
              <select value={warningType} onChange={e => setWarningType(e.target.value)} className="w-full bg-surfaceContainerLow p-3 rounded-xl border border-outlineVariant/20 outline-none focus:ring-2 focus:ring-primary text-sm font-bold">
                <option>عدم إرسال تقرير</option>
                <option>تأخر في العمل</option>
                <option>غياب بدون إذن</option>
                <option>مخالفة سياسات العمل</option>
                <option>أداء ضعيف</option>
                <option>سبب آخر</option>
              </select>
            </div>
            <div>
              <label className="text-xs font-bold text-onSurfaceVariant block mb-2">سبب التحذير التفصيلي:</label>
              <textarea required value={warningReason} onChange={e => setWarningReason(e.target.value)} rows={3} placeholder="اكتب سبب التحذير بالتفصيل..." className="w-full bg-surfaceContainerLow p-3 rounded-xl border border-outlineVariant/20 outline-none focus:ring-2 focus:ring-primary text-sm resize-none" />
            </div>
            <button type="submit" className="bg-error text-white font-bold p-4 rounded-xl hover:opacity-90 transition-opacity">إنشاء طلب التحذير ⚠️</button>
          </form>
        </div>
      )}

      {/* Issued Warnings Tab */}
      {tab === 'issued' && (
        <div className="flex flex-col gap-3">
          {issued.length === 0 ? (
            <div className="text-center p-16 text-onSurfaceVariant glass-card"><p>لا توجد تحذيرات صادرة حالياً.</p></div>
          ) : issued.map((warning: any) => (
            <div key={warning.id} className="glass-card p-4 flex items-center justify-between border-r-4 border-error">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-full flex items-center justify-center text-lg shrink-0 bg-error/10 text-error">
                  ⚠️
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-bold text-sm truncate">{warning.employee?.fullName || warning.employee?.name} — {warning.type}</p>
                  <p className="text-[10px] text-onSurfaceVariant mt-0.5">{warning.reason || 'بدون سبب إضافي'}</p>
                  <p className="text-[10px] text-onSurfaceVariant mt-0.5">صدر في: {new Date(warning.issuedAt).toLocaleDateString('ar-EG')}</p>
                </div>
              </div>
              <button 
                onClick={() => handleDeleteWarning(warning.id)}
                disabled={deletingWarningId === warning.id}
                className="bg-error/10 text-error hover:bg-error hover:text-white px-4 py-2 rounded-xl text-xs font-bold transition-colors shrink-0 disabled:opacity-50"
                title="تراجع عن اصدار هذا التحذير ومسحه نهائيا"
              >
                {deletingWarningId === warning.id ? 'يتم المسح...' : '🗑️ مسح التحذير'}
              </button>
            </div>
          ))}
        </div>
      )}

      {/* History Tab */}
      {tab === 'history' && (
        <div className="flex flex-col gap-3">
          {history.length === 0 ? (
            <div className="text-center p-16 text-onSurfaceVariant glass-card"><p>لا يوجد سجل تحذيرات.</p></div>
          ) : history.map(req => (
            <div key={req.id} className={`glass-card p-4 flex items-center gap-4 ${req.status === 'APPROVED' ? 'border-r-4 border-error' : req.status === 'REJECTED' ? 'border-r-4 border-success opacity-60' : 'border-r-4 border-warning'}`}>
              <div className="w-10 h-10 rounded-full flex items-center justify-center text-lg shrink-0" style={{ background: req.status === 'APPROVED' ? 'var(--error-10)' : req.status === 'REJECTED' ? 'var(--success-10)' : 'var(--warning-10)' }}>
                {req.status === 'APPROVED' ? '⚠️' : req.status === 'REJECTED' ? '✅' : '⏳'}
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-bold text-sm truncate">{req.employee?.name} — {req.type}</p>
                <p className="text-[10px] text-onSurfaceVariant mt-0.5">{req.reason}</p>
              </div>
              <span className={`text-[10px] font-bold px-3 py-1 rounded-full shrink-0 ${req.status === 'APPROVED' ? 'bg-error/10 text-error' : req.status === 'REJECTED' ? 'bg-success/10 text-success' : 'bg-warning/10 text-warning'}`}>
                {req.status === 'APPROVED' ? 'تمت الموافقة' : req.status === 'REJECTED' ? 'مرفوض' : 'بانتظار'}
              </span>
              <span className="text-[10px] text-onSurfaceVariant shrink-0">{new Date(req.createdAt).toLocaleDateString('ar-EG')}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
